### ISSUE TITLE
Add results diagram to the repo

### ISSUE THREAD

**Issue by vladimirkovacevic** [EmaPajic/Variant-Calling#3]
I really liked the diagram showing metric scores for different p values. Can you add it to the repo and Readme.md?
btw how come accuracy is stuck at 1.0 for all p values?
Also, can you add to the figure the number of variants?

**Comment by doraaki** [comment]
Thanks! Added several images to the repo, Remaining Readme.md chapters will be there soon.

As we have 2.8 million True Negatives and at most several tens of thousands of everything else, ACC = (TN + TP) / ALL is close to TN/TN=1.

Yes, we can add a figure with the number of variants.

**Comment by doraaki** [comment]
We wrote the Readme.md, added a figure with number of variants.
